### PR TITLE
WIP porting mvnsh to run latest Maven version 3.3.9

### PR DESCRIPTION
**Pull request by cpfeiffer**
- port from sonatype.sisu to eclipse.sisu
- port to eclipse.aether
- update code due to API changes (e.g. slf4j)
- update dependencies

Note that this needs gshell 3.0.0-SNAPSHOT from https://github.com/GEBIT/gshell

### CODE REVIEW

**Comment by cpfeiffer** [comment]
The error I am getting when starting mvnsh is this:

```
$ mvnsh 
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) null returned by binding at org.eclipse.sisu.wire.LocatorWiring
 but parameter 1 of org.apache.maven.classrealm.DefaultClassRealmManager.<init>() is not @Nullable
  while locating org.codehaus.plexus.PlexusContainer
    for parameter 1 at org.apache.maven.classrealm.DefaultClassRealmManager.<init>(DefaultClassRealmManager.java:96)
  at file:/home/gis/install/mvnsh-1.2.0-SNAPSHOT/lib/maven-core-3.3.9.jar!/ (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.apache.maven.classrealm.DefaultClassRealmManager
  while locating java.lang.Object annotated with *

2) null returned by binding at org.eclipse.sisu.wire.LocatorWiring
 but parameter 1 of org.apache.maven.classrealm.DefaultClassRealmManager.<init>() is not @Nullable
  while locating org.codehaus.plexus.PlexusContainer
    for parameter 1 at org.apache.maven.classrealm.DefaultClassRealmManager.<init>(DefaultClassRealmManager.java:96)
  at file:/home/gis/install/mvnsh-1.2.0-SNAPSHOT/lib/maven-core-3.3.9.jar!/ (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.apache.maven.classrealm.DefaultClassRealmManager

3) null returned by binding at org.eclipse.sisu.wire.LocatorWiring
 but parameter 0 of org.apache.maven.extension.internal.CoreExportsProvider.<init>() is not @Nullable
  while locating org.codehaus.plexus.PlexusContainer
    for parameter 0 at org.apache.maven.extension.internal.CoreExportsProvider.<init>(CoreExportsProvider.java:38)
  at file:/home/gis/install/mvnsh-1.2.0-SNAPSHOT/lib/maven-core-3.3.9.jar!/ (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.apache.maven.extension.internal.CoreExportsProvider
  while locating java.lang.Object annotated with *

4) null returned by binding at org.eclipse.sisu.wire.LocatorWiring
 but parameter 0 of org.apache.maven.extension.internal.CoreExportsProvider.<init>() is not @Nullable
  while locating org.codehaus.plexus.PlexusContainer
    for parameter 0 at org.apache.maven.extension.internal.CoreExportsProvider.<init>(CoreExportsProvider.java:38)
  at file:/home/gis/install/mvnsh-1.2.0-SNAPSHOT/lib/maven-core-3.3.9.jar!/ (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.apache.maven.extension.internal.CoreExportsProvider
    for parameter 1 at org.apache.maven.DefaultArtifactFilterManager.<init>(DefaultArtifactFilterManager.java:54)
  at file:/home/gis/install/mvnsh-1.2.0-SNAPSHOT/lib/maven-core-3.3.9.jar!/ (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.apache.maven.DefaultArtifactFilterManager
  while locating java.lang.Object annotated with *

5) null returned by binding at org.eclipse.sisu.wire.LocatorWiring
 but parameter 0 of org.apache.maven.extension.internal.CoreExportsProvider.<init>() is not @Nullable
  while locating org.codehaus.plexus.PlexusContainer
    for parameter 0 at org.apache.maven.extension.internal.CoreExportsProvider.<init>(CoreExportsProvider.java:38)
  at file:/home/gis/install/mvnsh-1.2.0-SNAPSHOT/lib/maven-core-3.3.9.jar!/ (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.apache.maven.extension.internal.CoreExportsProvider
    for parameter 3 at org.apache.maven.classrealm.DefaultClassRealmManager.<init>(DefaultClassRealmManager.java:96)
  at file:/home/gis/install/mvnsh-1.2.0-SNAPSHOT/lib/maven-core-3.3.9.jar!/ (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.apache.maven.classrealm.DefaultClassRealmManager
  while locating java.lang.Object annotated with *

6) null returned by binding at org.eclipse.sisu.wire.LocatorWiring
 but parameter 0 of org.apache.maven.extension.internal.CoreExportsProvider.<init>() is not @Nullable
  while locating org.codehaus.plexus.PlexusContainer
    for parameter 0 at org.apache.maven.extension.internal.CoreExportsProvider.<init>(CoreExportsProvider.java:38)
  at file:/home/gis/install/mvnsh-1.2.0-SNAPSHOT/lib/maven-core-3.3.9.jar!/ (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.apache.maven.extension.internal.CoreExportsProvider

7) null returned by binding at org.eclipse.sisu.wire.LocatorWiring
 but parameter 0 of org.apache.maven.extension.internal.CoreExportsProvider.<init>() is not @Nullable
  while locating org.codehaus.plexus.PlexusContainer
    for parameter 0 at org.apache.maven.extension.internal.CoreExportsProvider.<init>(CoreExportsProvider.java:38)
  at file:/home/gis/install/mvnsh-1.2.0-SNAPSHOT/lib/maven-core-3.3.9.jar!/ (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.apache.maven.extension.internal.CoreExportsProvider
    for parameter 1 at org.apache.maven.DefaultArtifactFilterManager.<init>(DefaultArtifactFilterManager.java:54)
  at file:/home/gis/install/mvnsh-1.2.0-SNAPSHOT/lib/maven-core-3.3.9.jar!/ (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.apache.maven.DefaultArtifactFilterManager

8) null returned by binding at org.eclipse.sisu.wire.LocatorWiring
 but parameter 0 of org.apache.maven.extension.internal.CoreExportsProvider.<init>() is not @Nullable
  while locating org.codehaus.plexus.PlexusContainer
    for parameter 0 at org.apache.maven.extension.internal.CoreExportsProvider.<init>(CoreExportsProvider.java:38)
  at file:/home/gis/install/mvnsh-1.2.0-SNAPSHOT/lib/maven-core-3.3.9.jar!/ (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.apache.maven.extension.internal.CoreExportsProvider
    for parameter 3 at org.apache.maven.classrealm.DefaultClassRealmManager.<init>(DefaultClassRealmManager.java:96)
  at file:/home/gis/install/mvnsh-1.2.0-SNAPSHOT/lib/maven-core-3.3.9.jar!/ (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.apache.maven.classrealm.DefaultClassRealmManager

9) null returned by binding at org.eclipse.sisu.wire.LocatorWiring
 but parameter 0 of org.apache.maven.classrealm.DefaultClassRealmManager.<init>() is not @Nullable
  while locating org.codehaus.plexus.logging.Logger
    for parameter 0 at org.apache.maven.classrealm.DefaultClassRealmManager.<init>(DefaultClassRealmManager.java:96)
  at file:/home/gis/install/mvnsh-1.2.0-SNAPSHOT/lib/maven-core-3.3.9.jar!/ (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.apache.maven.classrealm.DefaultClassRealmManager
  while locating java.lang.Object annotated with *

10) null returned by binding at org.eclipse.sisu.wire.LocatorWiring
 but parameter 0 of org.apache.maven.classrealm.DefaultClassRealmManager.<init>() is not @Nullable
  while locating org.codehaus.plexus.logging.Logger
    for parameter 0 at org.apache.maven.classrealm.DefaultClassRealmManager.<init>(DefaultClassRealmManager.java:96)
  at file:/home/gis/install/mvnsh-1.2.0-SNAPSHOT/lib/maven-core-3.3.9.jar!/ (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.space.SpaceModule)
  while locating org.apache.maven.classrealm.DefaultClassRealmManager

10 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at org.sonatype.gshell.guice.GuiceMainSupport.createShell(GuiceMainSupport.java:58)
        at org.sonatype.gshell.MainSupport.boot(MainSupport.java:275)
        at org.sonatype.maven.shell.Main.main(Main.java:70)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.sonatype.gshell.launcher.Launcher.launch(Launcher.java:75)
        at org.sonatype.gshell.launcher.Launcher.run(Launcher.java:47)
        at org.sonatype.gshell.launcher.Launcher.main(Launcher.java:38)
```

**Comment by cpfeiffer** [comment]
BTW, as you will probably notice, I don't know much about Maven yet, so I have surely made many mistakes.

**Comment by mcculls** [comment]
Re. the CreationException above - gshell creates its injector using `Stage.PRODUCTION` which will eagerly try to create any singleton bound in the injector:

https://github.com/GEBIT/gshell/blob/master/gshell-core/src/main/java/org/sonatype/gshell/guice/GuiceMainSupport.java#L58

where component bindings are discovered by looking for any jars which had a component index under `META-INF/sisu/javax.inject.Named`:

https://github.com/GEBIT/gshell/blob/master/gshell-core/src/main/java/org/sonatype/gshell/guice/GuiceMainSupport.java#L76

This wasn't an issue when only gshell jars had `META-INF/sisu/javax.inject.Named`, but Maven core 3.3.x includes this kind of component index. So Maven components like `DefaultClassRealmManager` are now being discovered by gshell, and because gshell uses `Stage.PRODUCTION` they are eagerly created at boot. And since Maven still uses a mix of `@Inject` and Plexus components you get the above exception, because it's expecting to find a surrounding Plexus container.

The easiest solution is to get quickly unblocked is to remove `Stage.PRODUCTION` from https://github.com/GEBIT/gshell/blob/master/gshell-core/src/main/java/org/sonatype/gshell/guice/GuiceMainSupport.java#L58 (ie. use the default stage) which turns off the eager creation of singletons.

The alternative is to add filtering to the discovery, which is feasible but a bit more involved (you can either filter the URLs when creating the class space, or provide a custom `ClassFinder` that does the filtering)

**Comment by cpfeiffer** [comment]
Awesome, thank you very much for your help. I will try your suggestions tomorrow, or at least next week. I'll let you know of the outcome and possibly update the pull request.

**Comment by jdillon** [comment]
thx @mcculls, I don't think there is a good reason why gshell couldn't use the default stage configuration.

**Comment by cpfeiffer** [comment]
First quick test: with the default stage, guice is happily wiring everything together and mvnsh starts up!

Something's still wrong though, because calling any mvn command yields the following error:

``
mvnsh(/):myproject> mvn clean
org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException                                                                                                                                                    
      role: org.apache.maven.execution.MavenExecutionRequestPopulator                                                                                                                                                                                            
  roleHint:
``

**Comment by jdillon** [comment]
@cpfeiffer I've not yet had a chance to look at the PR but will try and find time this weekend.  I'm sure some of the api changed since mvn command was first implemented that may need to get updated.

Can you open PR with the changes to gshell, doesn't look like stage change was in the set of commits on your branch.

The version of that stuff probably should be changed to 2.7.0-SNAPSHOT not 3.0.0-SNAPSHOT as this isn't going to be a major change to gshell framework and api, just updating some core libraries.

**Comment by cpfeiffer** [comment]
@jdillon Thanks, I just pushed the gshell changes and updated the mvnsh to use 2.7.0.

**Comment by jdillon** [comment]
@cpfeiffer I've pushed https://github.com/sonatype/gshell/pull/4 which includes some of your changes (and fixes to your changes) and gets the basic assembly of gshell working again and normalizes to more modern guice.  There is a bunch more clean up needed here, but this at least gets it buildable and functional again.

**Comment by jdillon** [comment]
@cpfeiffer pushed https://github.com/jdillon/mvnsh/pull/12

Unfortunately Maven still has a very poor embedder api.  The configuration of the MavenCli is very wonky but that class also does a lot of environment setup, which MavenSystem was duplicating to get better control over the aspects of the configuration.

I recommended to the Maven folks a lot time ago to fix this and follow something more simpler to what MavenSystem was doing, but alas that never happened, and the environment logic has become more complex to attempt to maintain this.

So I've removed all that and simply using MavenCli, with a minor hack to be able to actually configure package-private fields on CliRequest which is required to actually set the right bits.

I also disabled the archetype bits as I've no clue whats going on with those apis and I didn't feel too much like hacking it atm.

**Comment by cpfeiffer** [comment]
Wow, thanks a lot, that indeed makes it work! mvnsh starts up and I can invoke commands.

There's some problem with downloading artifacts, though:

mvnsh(/):pj-libs> mvn clean install
[INFO] Scanning for projects...
[WARN] Could not transfer metadata de.gebit.pj:pj:1.0.0-SNAPSHOT/maven-metadata.xml from/to snapshots (http://our.internal.nexus/content/repositories/snapshots): **No connector factories available**

And there's one little issue with the jline dependency in gshell. I had to bump the jline version from 2.3 to 2.5, because 2.3 depends on jansi 1.2, which is not publically available. It's supposed to be accessible from http://jansi.fusesource.org/, but that appears to be down.

**Comment by jdillon** [comment]
@cpfeiffer will have a closer look sometime later this week.  jline probably needs a lot more love to update to latest 2.x version but I've only took a quick look at this and it didn't just work, so will probably look more later.

**Comment by jdillon** [comment]
@cpfeiffer I've merged the gshell + mvnsh changes to each projects master.
* will have a closer look at jline
* updated mvnsh to include wagon deps

**Pull request closed without merging**
